robot:
  home_joint_positions:
    elbow_joint: -1.6648
    shoulder_lift_joint: -1.3542
    shoulder_pan_joint: -0.1597
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      latched: true
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  mount_rail:
    max_translation: 0.09425
    min_translation: -0.09425
  nic_rail:
    max_translation: 0.0234
    min_translation: -0.0215
  sc_rail:
    max_translation: 0.055
    min_translation: -0.06
trials:
  trial_1:
    scene:
      cables:
        cable_0:
          attach_cable_to_gripper: true
          cable_type: sfp_sc_cable
          pose:
            gripper_offset:
              x: -0.001907
              y: 0.014611
              z: 0.044319
            pitch: -0.462846
            roll: 0.454002
            yaw: 1.322228
      task_board:
        lc_mount_rail_0:
          entity_name: lc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.02
            yaw: 0.0
          entity_present: true
        lc_mount_rail_1:
          entity_name: lc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.01
            yaw: 0.0
          entity_present: true
        nic_rail_0:
          entity_present: false
        nic_rail_1:
          entity_name: nic_card_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.002071
            yaw: -0.034772
          entity_present: true
        nic_rail_2:
          entity_present: false
        nic_rail_3:
          entity_name: nic_card_3
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.019827
            yaw: 0.114456
          entity_present: true
        nic_rail_4:
          entity_present: false
        pose:
          pitch: 0.0
          roll: 0.0
          x: 0.165556
          y: -0.178133
          yaw: 3.179323
          z: 1.14
        sc_mount_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.02
            yaw: 0.0
          entity_present: true
        sc_mount_rail_1:
          entity_present: false
        sc_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.040156
            yaw: 0.0
          entity_present: true
        sc_rail_1:
          entity_name: sc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.004373
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_0:
          entity_name: sfp_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.03
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_1:
          entity_present: false
    tasks:
      task_1:
        cable_name: cable_0
        cable_type: sfp_sc
        plug_name: sfp_tip
        plug_type: sfp
        port_name: sfp_port_1
        port_type: sfp
        target_module_name: nic_card_mount_1
        time_limit: 30
