robot:
  home_joint_positions:
    elbow_joint: -1.6648
    shoulder_lift_joint: -1.3542
    shoulder_pan_joint: -0.1597
    wrist_1_joint: -1.6933
    wrist_2_joint: 1.571
    wrist_3_joint: 1.411
scoring:
  topics:
  - topic:
      name: /joint_states
      type: sensor_msgs/msg/JointState
  - topic:
      name: /tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      latched: true
      name: /tf_static
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /scoring/tf
      type: tf2_msgs/msg/TFMessage
  - topic:
      name: /aic/gazebo/contacts/off_limit
      type: ros_gz_interfaces/msg/Contacts
  - topic:
      name: /fts_broadcaster/wrench
      type: geometry_msgs/msg/WrenchStamped
  - topic:
      name: /aic_controller/joint_commands
      type: aic_control_interfaces/msg/JointMotionUpdate
  - topic:
      name: /aic_controller/pose_commands
      type: aic_control_interfaces/msg/MotionUpdate
  - topic:
      name: /scoring/insertion_event
      type: std_msgs/msg/String
  - topic:
      name: /aic_controller/controller_state
      type: aic_control_interfaces/msg/ControllerState
task_board_limits:
  mount_rail:
    max_translation: 0.09425
    min_translation: -0.09425
  nic_rail:
    max_translation: 0.0234
    min_translation: -0.0215
  sc_rail:
    max_translation: 0.055
    min_translation: -0.06
trials:
  trial_1:
    scene:
      cables:
        cable_0:
          attach_cable_to_gripper: true
          cable_type: sfp_sc_cable
          pose:
            gripper_offset:
              x: 0.001821
              y: 0.015063
              z: 0.041626
            pitch: -0.485302
            roll: 0.436475
            yaw: 1.366514
      task_board:
        lc_mount_rail_0:
          entity_name: lc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.02
            yaw: 0.0
          entity_present: true
        lc_mount_rail_1:
          entity_name: lc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.01
            yaw: 0.0
          entity_present: true
        nic_rail_0:
          entity_name: nic_card_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.022155
            yaw: 0.140842
          entity_present: true
        nic_rail_1:
          entity_name: nic_card_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.002455
            yaw: 0.10488
          entity_present: true
        nic_rail_2:
          entity_present: false
        nic_rail_3:
          entity_present: false
        nic_rail_4:
          entity_name: nic_card_4
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.000575
            yaw: -0.120256
          entity_present: true
        pose:
          pitch: 0.0
          roll: 0.0
          x: 0.165772
          y: -0.216609
          yaw: 3.177766
          z: 1.14
        sc_mount_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.02
            yaw: 0.0
          entity_present: true
        sc_mount_rail_1:
          entity_present: false
        sc_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.038972
            yaw: 0.0
          entity_present: true
        sc_rail_1:
          entity_present: false
        sfp_mount_rail_0:
          entity_name: sfp_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.03
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_1:
          entity_present: false
    tasks:
      task_1:
        cable_name: cable_0
        cable_type: sfp_sc
        plug_name: sfp_tip
        plug_type: sfp
        port_name: sfp_port_0
        port_type: sfp
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_2:
    scene:
      cables:
        cable_0:
          attach_cable_to_gripper: true
          cable_type: sfp_sc_cable
          pose:
            gripper_offset:
              x: 0.000758
              y: 0.017055
              z: 0.043725
            pitch: -0.500606
            roll: 0.448053
            yaw: 1.366342
      task_board:
        lc_mount_rail_0:
          entity_name: lc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.02
            yaw: 0.0
          entity_present: true
        lc_mount_rail_1:
          entity_name: lc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.01
            yaw: 0.0
          entity_present: true
        nic_rail_0:
          entity_name: nic_card_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.013139
            yaw: -0.10662
          entity_present: true
        nic_rail_1:
          entity_present: false
        nic_rail_2:
          entity_name: nic_card_2
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.016573
            yaw: -0.112626
          entity_present: true
        nic_rail_3:
          entity_present: false
        nic_rail_4:
          entity_name: nic_card_4
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.020837
            yaw: -0.172571
          entity_present: true
        pose:
          pitch: 0.0
          roll: 0.0
          x: 0.122742
          y: -0.233374
          yaw: 3.111715
          z: 1.14
        sc_mount_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.02
            yaw: 0.0
          entity_present: true
        sc_mount_rail_1:
          entity_present: false
        sc_rail_0:
          entity_present: false
        sc_rail_1:
          entity_name: sc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.035594
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_0:
          entity_name: sfp_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.03
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_1:
          entity_present: false
    tasks:
      task_1:
        cable_name: cable_0
        cable_type: sfp_sc
        plug_name: sfp_tip
        plug_type: sfp
        port_name: sfp_port_1
        port_type: sfp
        target_module_name: nic_card_mount_0
        time_limit: 180
  trial_3:
    scene:
      cables:
        cable_0:
          attach_cable_to_gripper: true
          cable_type: sfp_sc_cable
          pose:
            gripper_offset:
              x: 0.001505
              y: 0.013917
              z: 0.042552
            pitch: -0.507556
            roll: 0.433214
            yaw: 1.325019
      task_board:
        lc_mount_rail_0:
          entity_name: lc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.02
            yaw: 0.0
          entity_present: true
        lc_mount_rail_1:
          entity_name: lc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.01
            yaw: 0.0
          entity_present: true
        nic_rail_0:
          entity_present: false
        nic_rail_1:
          entity_name: nic_card_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.002085
            yaw: 0.15815
          entity_present: true
        nic_rail_2:
          entity_name: nic_card_2
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.017477
            yaw: -0.013466
          entity_present: true
        nic_rail_3:
          entity_name: nic_card_3
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.00087
            yaw: -0.044308
          entity_present: true
        nic_rail_4:
          entity_present: false
        pose:
          pitch: 0.0
          roll: 0.0
          x: 0.187976
          y: -0.206504
          yaw: 3.12941
          z: 1.14
        sc_mount_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.02
            yaw: 0.0
          entity_present: true
        sc_mount_rail_1:
          entity_present: false
        sc_rail_0:
          entity_present: false
        sc_rail_1:
          entity_name: sc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.020126
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_0:
          entity_name: sfp_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.03
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_1:
          entity_present: false
    tasks:
      task_1:
        cable_name: cable_0
        cable_type: sfp_sc
        plug_name: sfp_tip
        plug_type: sfp
        port_name: sfp_port_0
        port_type: sfp
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_4:
    scene:
      cables:
        cable_0:
          attach_cable_to_gripper: true
          cable_type: sfp_sc_cable
          pose:
            gripper_offset:
              x: -0.001907
              y: 0.014611
              z: 0.044319
            pitch: -0.462846
            roll: 0.454002
            yaw: 1.322228
      task_board:
        lc_mount_rail_0:
          entity_name: lc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.02
            yaw: 0.0
          entity_present: true
        lc_mount_rail_1:
          entity_name: lc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.01
            yaw: 0.0
          entity_present: true
        nic_rail_0:
          entity_present: false
        nic_rail_1:
          entity_name: nic_card_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.002071
            yaw: -0.034772
          entity_present: true
        nic_rail_2:
          entity_present: false
        nic_rail_3:
          entity_name: nic_card_3
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.019827
            yaw: 0.114456
          entity_present: true
        nic_rail_4:
          entity_present: false
        pose:
          pitch: 0.0
          roll: 0.0
          x: 0.165556
          y: -0.178133
          yaw: 3.179323
          z: 1.14
        sc_mount_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.02
            yaw: 0.0
          entity_present: true
        sc_mount_rail_1:
          entity_present: false
        sc_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.040156
            yaw: 0.0
          entity_present: true
        sc_rail_1:
          entity_name: sc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.004373
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_0:
          entity_name: sfp_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.03
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_1:
          entity_present: false
    tasks:
      task_1:
        cable_name: cable_0
        cable_type: sfp_sc
        plug_name: sfp_tip
        plug_type: sfp
        port_name: sfp_port_1
        port_type: sfp
        target_module_name: nic_card_mount_1
        time_limit: 180
  trial_5:
    scene:
      cables:
        cable_0:
          attach_cable_to_gripper: true
          cable_type: sfp_sc_cable
          pose:
            gripper_offset:
              x: -0.001085
              y: 0.016493
              z: 0.040503
            pitch: -0.472738
            roll: 0.434017
            yaw: 1.328284
      task_board:
        lc_mount_rail_0:
          entity_name: lc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.02
            yaw: 0.0
          entity_present: true
        lc_mount_rail_1:
          entity_name: lc_mount_1
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.01
            yaw: 0.0
          entity_present: true
        nic_rail_0:
          entity_present: false
        nic_rail_1:
          entity_present: false
        nic_rail_2:
          entity_name: nic_card_2
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.017491
            yaw: 0.003822
          entity_present: true
        nic_rail_3:
          entity_name: nic_card_3
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.006304
            yaw: 0.02437
          entity_present: true
        nic_rail_4:
          entity_name: nic_card_4
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.012678
            yaw: -0.046757
          entity_present: true
        pose:
          pitch: 0.0
          roll: 0.0
          x: 0.175575
          y: -0.209673
          yaw: 3.161758
          z: 1.14
        sc_mount_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: -0.02
            yaw: 0.0
          entity_present: true
        sc_mount_rail_1:
          entity_present: false
        sc_rail_0:
          entity_name: sc_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.027672
            yaw: 0.0
          entity_present: true
        sc_rail_1:
          entity_present: false
        sfp_mount_rail_0:
          entity_name: sfp_mount_0
          entity_pose:
            pitch: 0.0
            roll: 0.0
            translation: 0.03
            yaw: 0.0
          entity_present: true
        sfp_mount_rail_1:
          entity_present: false
    tasks:
      task_1:
        cable_name: cable_0
        cable_type: sfp_sc
        plug_name: sfp_tip
        plug_type: sfp
        port_name: sfp_port_0
        port_type: sfp
        target_module_name: nic_card_mount_2
        time_limit: 180
